---
- name: Kubeadm reset
  command: "kubeadm reset"
  tags:
    - k8s

- name: Kubeadm init
  command: "kubeadm init --token=2f1a31.00f66dec74fd53f3 --pod-network-cidr 10.244.0.0/16 --apiserver-advertise-address 192.168.33.11 --skip-preflight-checks=true"
  tags:
    - k8s

- name: Apply fannel RDAC config
  command: "kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel-rbac.yml"
  tags:
    - k8s

- name: Download fannel config
  get_url:
    url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    dest: /tmp/kube-flannel.yml
  tags:
    - k8s

- name: Specify network interface for flannel
  # Specify flannel use enp0s8 network interface (for private network) instead of the default one (vagrant default NAT)
  lineinfile:
    path: /tmp/kube-flannel.yml
    regexp: '^(.*"--kube-subnet-mgr") ]$'
    line: '\1, "--iface=enp0s8" ]'
    backrefs: yes
  tags:
    - k8s

- name: Apply fannel config
  command: "kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /tmp/kube-flannel.yml"
  tags:
    - k8s

- name: Remove tmp fannel config
  file:
    path: /tmp/kube-flannel.yml
    state: absent
  tags:
    - k8s

- name: Install K8S dashboard
  command: "kubectl --kubeconfig=/etc/kubernetes/admin.conf create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml"
  tags:
    - k8s
